services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - infra
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - infra
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./configs/loki/local-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - infra
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - "--web.enable-remote-write-receiver"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus_data:/prometheus
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  alloy:
    image: grafana/alloy
    container_name: alloy
    hostname: "infrastructure"
    restart: unless-stopped
    ports:
      - "12345:12345"
    networks:
      - infra
    volumes:
      - alloy_data:/var/lib/alloy/data
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - infra
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    privileged: true
    networks:
      - infra
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /run/udev:/run/udev:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs

volumes:
  prometheus_data:
  grafana-data:
  loki_data:
  alloy_data:

networks:
  infra:
    driver: bridge
